unweighted_graph = {
    "Asmara": ["Axum", "Adigrat"],
    "Axum": ["Asmara", "Adwa", "Shire"],
    "Adigrat": ["Axum", "Killbeh Rasu"],
    "Killbeh Rasu": ["Adigrat", "Fanti Rasu"],
    "Fanti Rasu": ["Killbeh Rasu", "Kemise", "Amhara"],
    "Kemise": ["Fanti Rasu", "Dessie"],
    "Dessie": ["Kemise", "Lalibela"],
    "Lalibela": ["Dessie", "Debre Markos", "Debark"],
    "Debark": ["Lalibela", "Gondar", "Sekota"],
    "Gondar": ["Debark", "Bahirdar", "Metema"],
    "Bahirdar": ["Gondar", "Debre Markos", "Finote Selam"],
    "Debre Markos": ["Lalibela", "Bahirdar", "Addis Ababa"],
    "Addis Ababa": ["Debre Markos", "Finote Selam", "Ambo", "Adama"],
    "Finote Selam": ["Bahirdar", "Addis Ababa", "Jima"],
    "Ambo": ["Addis Ababa", "Woliso"],
    "Woliso": ["Ambo", "Jima", "Dawro"],
    "Jima": ["Woliso", "Bonga", "Metu"],
    "Dawro": ["Woliso", "Hosaena", "Bonga"],
    "Bonga": ["Jima", "Dawro", "Tepi"],
    "Tepi": ["Bonga", "Gore"],
    "Gore": ["Tepi", "Metu"],
    "Metu": ["Jima", "Gore", "Gambela"],
    "Gambela": ["Metu", "Assosa"],
    "Assosa": ["Gambela", "Demidollo"],
    "Demidollo": ["Assosa", "Gimbi"],
    "Gimbi": ["Demidollo", "Nekemte"],
    "Nekemte": ["Gimbi", "Ambo"],
    "Hosaena": ["Dawro", "Sodo", "Buta Jira"],
    "Sodo": ["Hosaena", "Arba Minch"],
    "Arba Minch": ["Sodo", "Konso"],
    "Konso": ["Arba Minch", "Yabelo"],
    "Yabelo": ["Konso", "Moyale"],
    "Moyale": ["Yabelo", "Marsabit"],
    "Buta Jira": ["Hosaena", "Adama"],
    "Adama": ["Buta Jira", "Addis Ababa", "Bishoftu"],
    "Bishoftu": ["Adama", "Dodola", "Assella"],
    "Dodola": ["Bishoftu", "Bale"],
    "Bale": ["Dodola", "Goba"],
    "Goba": ["Bale", "Sol Oumer"],
    "Sol Oumer": ["Goba", "Liben"],
    "Liben": ["Sol Oumer", "Dollo"],
    "Dollo": ["Liben", "Kebri Dehar"],
    "Kebri Dehar": ["Dollo", "Gode"],
    "Gode": ["Kebri Dehar", "Dega Habur"],
    "Dega Habur": ["Gode", "Harar"],
    "Harar": ["Dega Habur", "Chiro"],
    "Chiro": ["Harar", "Adama", "Metehara"],
    "Metehara": ["Chiro", "Awash"],
    "Awash": ["Metehara", "Dire Dawa"],
    "Dire Dawa": ["Awash", "Babile"],
    "Babile": ["Dire Dawa", "Doghabur"],
    "Doghabur": ["Babile", "Hargeisa"]
}

weighted_graph = {
    "Asmara": [("Axum", 8), ("Adigrat", 6)],
    "Axum": [("Asmara", 8), ("Adwa", 5), ("Shire", 8)],
    "Adwa": [("Axum", 5)],
    "Shire": [("Axum", 8), ("Humera", 9)],
    "Adigrat": [("Asmara", 6), ("Killbeh Rasu", 6)],
    "Killbeh Rasu": [("Adigrat", 6), ("Fanti Rasu", 6)],
    "Fanti Rasu": [("Killbeh Rasu", 6), ("Amhara", 11), ("Kemise", 8)],
    "Kemise": [("Fanti Rasu", 8), ("Dessie", 7)],
    "Dessie": [("Kemise", 7), ("Lalibela", 11)],
    "Lalibela": [("Dessie", 11), ("Debark", 12), ("Debre Markos", 17)],
    "Debark": [("Lalibela", 12), ("Gondar", 7)],
    "Gondar": [("Debark", 7), ("Metema", 7), ("Bahirdar", 4)],
    "Bahirdar": [("Gondar", 4), ("Debre Markos", 11), ("Finote Selam", 8)],
    "Debre Markos": [("Lalibela", 17), ("Bahirdar", 11), ("Addis Ababa", 6)],
    "Finote Selam": [("Bahirdar", 8), ("Addis Ababa", 6)],
    "Addis Ababa": [("Debre Markos", 6), ("Finote Selam", 6), ("Ambo", 6), ("Adama", 3)],
    "Ambo": [("Addis Ababa", 6), ("Woliso", 4), ("Nekemte", 9)],
    "Woliso": [("Ambo", 4), ("Jima", 6), ("Dawro", 6)],
    "Jima": [("Woliso", 6), ("Bonga", 7), ("Metu", 4)],
    "Dawro": [("Woliso", 6), ("Hosaena", 6), ("Bonga", 9)],
    "Bonga": [("Jima", 7), ("Dawro", 9), ("Tepi", 9)],
    "Tepi": [("Bonga", 9), ("Gore", 4)],
    "Gore": [("Tepi", 4), ("Metu", 4)],
    "Metu": [("Gore", 4), ("Jima", 4), ("Gambela", 12)],
    "Gambela": [("Metu", 12), ("Assosa", 4)],
    "Assosa": [("Gambela", 4), ("Demidollo", 12)],
    "Demidollo": [("Assosa", 12), ("Gimbi", 6)],
    "Gimbi": [("Demidollo", 6), ("Nekemte", 8)],
    "Nekemte": [("Gimbi", 8), ("Ambo", 9)],
    "Hosaena": [("Dawro", 6), ("Sodo", 7), ("Buta Jira", 8)],
    "Sodo": [("Hosaena", 7), ("Arba Minch", 7)],
    "Arba Minch": [("Sodo", 7), ("Konso", 6)],
    "Konso": [("Arba Minch", 6), ("Yabelo", 6)],
    "Yabelo": [("Konso", 6), ("Moyale", 22)],
    "Moyale": [("Yabelo", 22), ("Marsabit", 22)],
    "Buta Jira": [("Hosaena", 8), ("Adama", 4)],
    "Adama": [("Buta Jira", 4), ("Addis Ababa", 3), ("Bishoftu", 3)],
    "Bishoftu": [("Adama", 3), ("Dodola", 6), ("Assella", 6)],
    "Dodola": [("Bishoftu", 6), ("Bale", 6)],
    "Bale": [("Dodola", 6), ("Goba", 6)],
    "Goba": [("Bale", 6), ("Sol Oumer", 18)],
    "Sol Oumer": [("Goba", 18), ("Liben", 23)],
    "Liben": [("Sol Oumer", 23), ("Dollo", 11)],
    "Dollo": [("Liben", 11), ("Kebri Dehar", 17)],
    "Kebri Dehar": [("Dollo", 17), ("Gode", 6)],
    "Gode": [("Kebri Dehar", 6), ("Dega Habur", 5)],
    "Dega Habur": [("Gode", 5), ("Harar", 28)],
    "Harar": [("Dega Habur", 28), ("Chiro", 4)],
    "Chiro": [("Harar", 4), ("Adama", 6), ("Metehara", 3)],
    "Metehara": [("Chiro", 3), ("Awash", 4)],
    "Awash": [("Metehara", 4), ("Dire Dawa", 8)],
    "Dire Dawa": [("Awash", 8), ("Babile", 4)],
    "Babile": [("Dire Dawa", 4), ("Doghabur", 3)],
    "Doghabur": [("Babile", 3), ("Hargeisa", 5)],
    "Hargeisa": [("Doghabur", 5)]
}


heuristics = {
    "Kartum": 81,
    "Humera": 65,
    "Shire": 67,
    "Axum": 66,
    "Adigrat": 62,
    "Asmera":68,
    "Adwa": 65,
    "Debarke": 60,
    "Gondar": 56,
    "Mekelle":58,
    "Sekota": 59,
    "Metema":62,
    "Azezo":55,
    "Meketel":59,
    "Injibara":44,
    "Finoteselam":42,
    "Debremarkos":39,
    "Bahirdar":48,
    "Debretabor":52,
    "Lalibela":57,
    "Dessie": 44,
    "Kemise": 40,
    "Debresina":33,
    "Debrebirhan":31,
    "Addisababa": 26,
    "Ambo":31,
    "Nekemete":39,
    "Gimbi":43,
    "Assosa":51,
    "Dembidollo":49,
    "Gambella":51,
    "Gore":46,
    "Tepi":41,
    "Mezanteferi":37,
    "Bonga":33,
    "Jimma":33,
    "Dawro":23,
    "Basketo":23,
    "Benchmaji":28,
    "Juba":50,
    "Arbaminch":13,
    "Konso":9,
    "Wolaitasodo":17,
    "Hossana":21,
    "Bedelle":40,
    "Wolkite":25,
    "Butajirra":21,
    "Worabe":22,
    "Adama":23,
    "Batu":19,
    "Shashemene":16,
    "Hawassa":15,
    "Dilla":12,
    "Bulehora":8,
    "Yabello":6,
    "Alamata":53,
    "Woldia":50,
    "Kilbetrasu":55,
    "Fantirasu":49,
    "Samara":42,
    "Gabirasu":32,
    "Matahara":26,
    "Assella":22,
    "Assasa":18,
    "Dodolla":19,
    "Robe":22,
    "Liben":11,
    "Moyale": 0,
    "Nairobi" : 22,
    "Dollo": 18,
    "Mokadisho":40,
    "Gode":35,
    "Kebridehan":40,
    "Werder":46,
    "Sofoumer":45,
    "Goba":40,
    "Degahabur": 45,
    "Jigjiga":40,
    "Babile": 37,
    "Harar":35,
    "Diredawa":31,
    "Chiro":31,
    "Awash":27
}

adversarial_graph = {
    "Addis Ababa": ["Ambo", "Buta Jirra", "Adama"],
    "Ambo": ["Gedo", "Nekemte"],
    "Buta Jirra": ["Worabe", "Wolkite"],
    "Adama": ["Diredawa", "Mojo"],
    "Gedo": ["Shambu", "Fincha"],
    "Nekemte": ["Gimbi", "Limu"],
    "Worabe": ["Hossana", "Durame"],
    "Wolkite": ["Bench Maji", "Tepi"],
    "Mojo": ["Kaffa", "Dilla"],
    "Diredawa": ["Harar", "Chiro"]
}
reward_map = {
    "Fincha": 5,
    "Shambu": 4,
    "Gimbi": 8,
    "Limu": 8,
    "Hossana": 6,
    "Durame": 5,
    "Bench Maji": 5,
    "Tepi": 6,
    "Kaffa": 7,
    "Dilla": 9,
    "Chiro": 6,
    "Harar": 10
}
