unweighted_graph = {
    
        "Kartum": ["Metema", "Humera"],
        "Humera": ["Gondar", "Kartum", "Shire"],
        "Metema": ["Gondar", "Azezo"],
        "Debarke": ["Gondar", "Shire"],
        "Shire": ["Humera", "Axum"],
        "Gondar": ["Azezo", "Debarke", "Humera"],
        "Azezo": ["Gondar", "Metema", "Bahirdar"],
        "Axum": ["Shire", "Adwa", "Asmera"],
        "Asmera": ["Axum", "Adigrat"],
        "Adwa": ["Axum", "Adigrat", "Mekelle"],
        "Adigrat": ["Adwa", "Mekelle"],
        "Bahirdar": ["Metekel", "Debretabor", "Injibara", "Finoteselam","Azezo"],
        "Metekel": ["Bahirdar"],
        "Injibara": ["Bahirdar", "Finoteselam"],
        "Finoteselam": ["Injibara", "Bahirdar", "Debremarkos"],
        "Debremarkos": ["Debresina"],
        "Debresina": ["Debrebirhan", "Kemise"],
        "Kilbetrasu": ["Fantirasu"],
        "Mekelle": ["Sekota", "Alamata", "Adigrat", "Adwa"],
        "Sekota": ["Mekelle", "Lalibela", "Alamata"],
        "Alamata": ["Woldia", "Samara", "Sekota", "Mekelle"],
        "Fantirasu": ["Kilbetrasu", "Samara"],
        "Debretabor": ["Bahirdar", "Lalibela"],
        "Lalibela": ["Debretabor", "Sekota", "Woldia"],
        "Woldia": ["Lalibela", "Alamata", "Samara"],
        "Samara": ["Alamata", "Woldia", "Fantirasu", "Gabirasu"],
        "Dessie": ["Woldia", "Kemise"],
        "Kemise": ["Dessie", "Debresina"],
        "Gabirasu": ["Samara", "Awash"],
        "Debrebirhan": ["Debresina", "Addisababa"],
        "Addisababa": ["Debrebirhan", "Ambo", "Adama"],
        "Ambo": ["Nekemete", "Addisababa", "Wolkite"],
        "Awash": ["Chiro", "Matahara"],
        "Chiro": ["Awash", "Diredawa"],
        "Diredawa": ["Chiro", "Harar"],
        "Harar": ["Diredawa", "Babile"],
        "Nekemete": ["Ambo", "Gimbi", "Bedelle"],
        "Gimbi": ["Nekemete", "Dembidollo"],
        "Dembidollo": ["Assosa", "Gambella"],
        "Assosa": ["Dembidollo"],
        "Gambella": ["Dembidollo", "Gore"],
        "Gore": ["Gambella", "Bedelle", "Tepi"],
        "Bedelle": ["Nekemete", "Gore", "Jimma"],
        "Tepi": ["Bonga", "Mezanteferi", "Gore"],
        "Bonga": ["Tepi", "Mezanteferi"],
        "Jimma": ["Bedelle", "Bonga", "Wolkite"],
        "Dawro": ["Bonga", "Wolaitasodo"],
        "Wolaitasodo": ["Dawro", "Hossana"],
        "Hossana": ["Wolaitasodo", "Worabe", "Shashemene"],
        "Wolkite": ["Jimma", "Worabe", "Ambo"],
        "Butajirra": ["Worabe", "Batu"],
        "Worabe": ["Hossana", "Butajirra", "Wolkite"],
        "Dilla": ["Bulehora", "Hawassa"],
        "Hawassa": ["Dilla", "Shashemene"],
        "Juba": ["Benchmaji"],
        "Benchmaji": ["Juba", "Basketo"],
        "Basketo": ["Arbaminch", "Benchmaji"],
        "Arbaminch": ["Konso", "Wolaitasodo", "Basketo"],
        "Bulehora": ["Yabello", "Dilla"],
        "Konso": ["Yabello", "Arbaminch"],
        "Yabello": ["Moyale", "Bulehora", "Konso"],
        "Moyale": ["Nairobi", "Yabello"],
        "Nairobi": ["Moyale"],
        "Matahara": ["Awash", "Adama"],
        "Assasa": ["Assella", "Dodolla"],
        "Assella": ["Adama", "Assasa"],
        "Adama": ["Batu", "Assella", "Matahara", "Addisababa"],
        "Batu": ["Shashemene", "Butajirra", "Adama"],
        "Shashemene": ["Dodolla", "Hawassa", "Hossana", "Batu"],
        "Dodolla": ["Bale", "Assasa", "Shashemene"],
        "Bale": ["Liben", "Sofoumer", "Goba", "Dodolla"],
        "Liben": ["Bale"],
        "Sofoumer": ["Gode", "Bale", "Goba"],
        "Goba": ["Babile", "Sofoumer", "Bale"],
        "Babile": ["Jigjiga", "Goba", "Harar"],
        "Jigjiga": ["Degahabur", "Babile"],
        "Degahabur": ["Kebridehar", "Jigjiga"],
        "Werder": ["Kebridehar"],
        "Kebridehar": ["Gode", "Werder", "Degahabur"],
        "Dollo": ["Gode"],
        "Gode": ["Mokadisho", "Sofoumer", "Dollo", "Kebridehar"],
        "Mokadisho": ["Gode"],
        "Mezanteferi":["Tepi","Bonga"]

}

weighted_graph = {
    "Kartum": [("Metema", 19), ("Humera", 21)],
    "Humera": [("Gondar", 9), ("Kartum", 21), ("Shire", 8)],
    "Metema": [("Gondar", 7), ("Azezo", 7)],
    "Debarke": [("Gondar", 4), ("Shire", 7)],
    "Shire": [("Humera", 8), ("Axum", 2)],
    "Gondar": [("Azezo", 1), ("Debarke", 4), ("Humera", 9)],
    "Azezo": [("Gondar", 1), ("Metema", 7), ("Bahirdar", 7)],
    "Axum": [("Shire", 2), ("Adwa", 1), ("Asmera", 5)],
    "Asmera": [("Axum", 5), ("Adigrat", 6)],
    "Adwa": [("Axum", 1), ("Adigrat", 4), ("Mekelle", 7)],
    "Adigrat": [("Adwa", 4), ("Mekelle", 4)],
    "Bahirdar": [
        ("Metekel", 11),
        ("Debretabor", 4),
        ("Injibara", 4),
        ("Finoteselam", 6),
        ("Azezo", 7),

    ],
    "Metekel": [("Bahirdar", 11)],
    "Injibara": [("Bahirdar", 4), ("Finoteselam", 2)],
    "Finoteselam": [("Injibara", 2), ("Bahirdar", 6), ("Debremarkos", 3)],
    "Debremarkos": [("Debresina", 17)],
    "Debresina": [("Debrebirhan", 2), ("Kemise", 6)],
    "Kilbetrasu": [("Fantirasu", 6)],
    "Mekelle": [("Sekota", 9), ("Alamata", 5), ("Adigrat", 4), ("Adwa", 7)],
    "Sekota": [("Mekelle", 9), ("Lalibela", 6), ("Alamata", 6)],
    "Alamata": [("Woldia", 3), ("Samara", 11), ("Sekota", 6), ("Mekelle", 5)],
    "Fantirasu": [("Kilbetrasu", 6), ("Samara", 7)],
    "Debretabor": [("Bahirdar", 4), ("Lalibela", 8)],
    "Lalibela": [("Debretabor", 8), ("Sekota", 6), ("Woldia", 7)],
    "Woldia": [("Lalibela", 7), ("Alamata", 3), ("Samara", 8)],
    "Samara": [("Alamata", 11), ("Woldia", 8), ("Fantirasu", 7), ("Gabirasu", 9)],
    "Dessie": [("Woldia", 6), ("Kemise", 4)],
    "Kemise": [("Dessie", 4), ("Debresina", 6)],
    "Gabirasu": [("Samara", 9), ("Awash", 5)],
    "Debrebirhan": [("Debresina", 2), ("Addisababa", 5)],
    "Addisababa": [("Debrebirhan", 5), ("Ambo", 5), ("Adama", 3)],
    "Ambo": [("Nekemete", 9), ("Addisababa", 5), ("Wolkite", 6)],
    "Awash": [("Chiro", 4), ("Matahara", 1)],
    "Chiro": [("Awash", 4), ("Diredawa", 9)],
    "Diredawa": [("Chiro", 8), ("Harar", 4)],
    "Harar": [("Diredawa", 4), ("Babile", 2)],
    "Nekemete": [("Ambo", 9), ("Gimbi", 4), ("Bedelle", 2)],
    "Gimbi": [("Nekemete", 4), ("Dembidollo", 6)],
    "Dembidollo": [("Assosa", 12), ("Gambella", 4)],
    "Assosa": [("Dembidollo", 12)],
    "Gambella": [("Dembidollo", 4), ("Gore", 5)],
    "Gore": [("Gambella", 5), ("Bedelle", 6), ("Tepi", 9)],
    "Bedelle": [("Nekemete", 2), ("Gore", 6), ("Jimma", 7)],
    "Tepi": [("Bonga", 8), ("Mezanteferi", 4), ("Gore", 9)],
    "Bonga": [("Tepi", 8), ("Mezanteferi", 4)],
    "Jimma": [("Bedelle", 7), ("Bonga", 4), ("Wolkite", 8)],
    "Dawro": [("Bonga", 10), ("Wolaitasodo",6)],
    "Wolaitasodo": [("Dawro", 6), ("Hossana", 4)],
    "Hossana": [("Wolaitasodo", 4), ("Worabe", 2), ("Shashemene", 7)],
    "Wolkite": [("Jimma", 8), ("Worabe", 5), ("Ambo", 6)],
    "Butajirra": [("Worabe", 2), ("Batu", 2)],
    "Worabe": [("Hossana", 2), ("Butajirra", 2), ("Wolkite", 5)],
    "Dilla": [("Bulehora", 4), ("Hawassa", 3)],
    "Hawassa": [("Dilla", 3), ("Shashemene", 1)],
    "Juba": [("Benchmaji", 22)],
    "Benchmaji": [("Juba", 22), ("Basketo", 5)],
    "Basketo": [("Arbaminch", 10), ("Benchmaji", 5)],
    "Arbaminch": [("Konso", 4), ("Wolaitasodo", 2), ("Basketo", 10)],
    "Bulehora": [("Yabello", 3), ("Dilla", 4)],
    "Konso": [
        ("Yabello", 3),
        ("Arbaminch", 4),
    ],
    "Yabello": [("Moyale", 6), ("Bulehora", 3), ("Konso", 3)],
    "Moyale": [("Nairobi", 22), ("Yabello", 6)],
    "Nairobi": [("Moyale", 22)],
    "Matahara": [("Awash", 1), ("Adama", 3)],
    "Assasa": [("Assella", 4), ("Dodolla", 1)],
    "Assella": [("Adama", 4), ("Assasa", 4)],
    "Adama": [("Batu", 4), ("Assella", 4), ("Matahara", 3), ("Addisababa", 3)],
    "Batu": [("Shashemene", 3), ("Butajirra", 2), ("Adama", 4)],
    "Shashemene": [("Dodolla", 3), ("Hawassa", 1), ("Hossana", 7), ("Batu", 3)],
    "Dodolla": [("Bale", 13), ("Assasa", 1), ("Shashemene", 3)],
    "Bale": [("Liben", 11), ("Sofoumer", 23), ("Goba", 18), ("Dodolla", 13)],
    "Liben": [("Bale", 11)],
    "Sofoumer": [("Gode", 23), ("Bale", 23), ("Goba", 6)],
    "Goba": [
        ("Babile", 28),
        ("Sofoumer", 6),
        ("Bale", 18),
    ],
    "Babile": [("Jigjiga", 3), ("Goba", 28), ("Harar", 2)],
    "Jigjiga": [("Degahabur", 5), ("Babile", 3)],
    "Degahabur": [("Kebridehar", 6), ("Jigjiga", 5)],
    "Werder": [("Kebridehar", 6)],
    "Kebridehar": [("Gode", 5), ("Werder", 6), ("Degahabur", 6)],
    "Dollo": [("Gode", 17)],
    "Gode": [("Mokadisho", 22), ("Sofoumer", 23), ("Dollo", 17), ("Kebridehar", 5)],
    "Mokadisho": [("Gode", 22)],
    "Mezanteferi":[("Tepi",4),("Bonga",4)]
}


heuristics = {
    "Kartum": 81,
    "Humera": 65,
    "Shire": 67,
    "Axum": 66,
    "Adigrat": 62,
    "Asmera": 68,
    "Adwa": 65,
    "Debarke": 60,
    "Gondar": 56,
    "Mekelle": 58,
    "Sekota": 59,
    "Metema": 62,
    "Azezo": 55,
    "Meketel": 59,
    "Injibara": 44,
    "Finoteselam": 42,
    "Debremarkos": 39,
    "Bahirdar": 48,
    "Debretabor": 52,
    "Lalibela": 57,
    "Dessie": 44,
    "Kemise": 40,
    "Debresina": 33,
    "Debrebirhan": 31,
    "Addisababa": 26,
    "Ambo": 31,
    "Nekemete": 39,
    "Gimbi": 43,
    "Assosa": 51,
    "Dembidollo": 49,
    "Gambella": 51,
    "Gore": 46,
    "Tepi": 41,
    "Mezanteferi": 37,
    "Bonga": 33,
    "Jimma": 33,
    "Dawro": 23,
    "Basketo": 23,
    "Benchmaji": 28,
    "Juba": 50,
    "Arbaminch": 13,
    "Konso": 9,
    "Wolaitasodo": 17,
    "Hossana": 21,
    "Bedelle": 40,
    "Wolkite": 25,
    "Butajirra": 21,
    "Worabe": 22,
    "Adama": 23,
    "Batu": 19,
    "Shashemene": 16,
    "Hawassa": 15,
    "Dilla": 12,
    "Bulehora": 8,
    "Yabello": 6,
    "Alamata": 53,
    "Woldia": 50,
    "Kilbetrasu": 55,
    "Fantirasu": 49,
    "Samara": 42,
    "Gabirasu": 32,
    "Matahara": 26,
    "Assella": 22,
    "Assasa": 18,
    "Dodolla": 19,
    "Robe": 22,
    "Liben": 11,
    "Moyale": 0,
    "Nairobi": 22,
    "Dollo": 18,
    "Mokadisho": 40,
    "Gode": 35,
    "Kebridehan": 40,
    "Werder": 46,
    "Sofoumer": 45,
    "Goba": 40,
    "Degahabur": 45,
    "Jigjiga": 40,
    "Babile": 37,
    "Harar": 35,
    "Diredawa": 31,
    "Chiro": 31,
    "Awash": 27,
}

adversarial_graph = {
    "Addis Ababa": ["Ambo", "Buta Jirra", "Adama"],
    "Ambo": ["Gedo", "Nekemte"],
    "Buta Jirra": ["Worabe", "Wolkite"],
    "Adama": ["Diredawa", "Mojo"],
    "Gedo": ["Shambu", "Fincha"],
    "Nekemte": ["Gimbi", "Limu"],
    "Worabe": ["Hossana", "Durame"],
    "Wolkite": ["Bench Maji", "Tepi"],
    "Mojo": ["Kaffa", "Dilla"],
    "Diredawa": ["Harar", "Chiro"],
}
reward_map = {
    "Fincha": 5,
    "Shambu": 4,
    "Gimbi": 8,
    "Limu": 8,
    "Hossana": 6,
    "Durame": 5,
    "Bench Maji": 5,
    "Tepi": 6,
    "Kaffa": 7,
    "Dilla": 9,
    "Chiro": 6,
    "Harar": 10,
}
